# Generated by Django 2.2.6 on 2020-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0002_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tribaluser',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tribaluser',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tribaluser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
