# Generated by Django 2.2.6 on 2020-01-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0003_auto_20200115_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TribalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='skillpics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
