# Generated by Django 2.2.6 on 2020-01-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0004_tribalskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribalskills',
            name='img',
        ),
        migrations.AlterField(
            model_name='tribalskills',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
