# Generated by Django 2.2.6 on 2020-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0007_auto_20200116_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalskills',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
