# Generated by Django 2.2.6 on 2020-01-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0008_auto_20200116_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribaluser',
            old_name='name',
            new_name='type_user',
        ),
        migrations.RemoveField(
            model_name='tribaluser',
            name='password',
        ),
    ]
