# Generated by Django 2.2.6 on 2020-01-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0009_auto_20200117_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribaluser',
            name='type_user',
            field=models.CharField(max_length=60),
        ),
    ]
