# Generated by Django 2.2.6 on 2020-01-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0010_auto_20200117_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribalskills',
            name='img',
            field=models.ImageField(default=' ', upload_to='pics/'),
        ),
    ]
