# Generated by Django 2.2.6 on 2020-01-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0011_auto_20200117_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribalskills',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tribalskills',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tribalskills',
            name='name',
        ),
    ]
