# Generated by Django 2.2.6 on 2020-01-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0013_auto_20200117_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribalskills',
            name='email',
            field=models.CharField(default=' ', max_length=80),
        ),
    ]
