# Generated by Django 2.2.6 on 2020-01-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0018_invite_tribal_to_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_tribal_to_org',
            name='status',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='invite_tribal_to_org',
            name='status',
            field=models.CharField(default='', max_length=80),
        ),
    ]
