# Generated by Django 2.2.6 on 2020-01-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0019_auto_20200120_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='tribaluser',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
