# Generated by Django 2.2.6 on 2020-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0020_auto_20200122_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='typeorg',
            field=models.CharField(default='', max_length=50),
        ),
    ]
