# Generated by Django 2.2.6 on 2020-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0021_organisation_typeorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
