# Generated by Django 2.2.6 on 2020-01-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0022_auto_20200122_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='mobile',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
